#!/bin/bash -l
#SBATCH -A AST20011 
#SBATCH --job-name="THIN_RAD_MAD"
#SBATCH --mail-type=ALL
#SBATCH --mail-user=matthewliska92@gmail.com
#SBATCH -t 01:00:00
#SBATCH -p v100
#SBATCH -N 1 #Number of nodes
#SBATCH -n 1 # Number of cores

module load gcc
module load python3
source /scratch/03284/tg825826/HAMR5/bin/activate

srun -n 1 python3 pp.py build_ext --inplace